# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='long_url',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
